### PR TITLE
Improved file handling

### PR DESCRIPTION
**Pull request by gorenburg**
# Fix
Fix cases when 'in' is returned as array instead of string

# Improvements
Added two more arguments of merging filename keys and translation keys and default language merge filename

### CODE REVIEW

**Comment by marcioggs** [comment]
Thanks for your contribution @gorenburg. 
You added valuable features that I'm going to use myself :) 
I'll take a look this weekend at the latest.

**Comment by gorenburg** [comment]
@marcioggs you're welcome!

**Comment by marcioggs** [comment]
I'm new to Angular i18n and I'm trying to understand the use cases that the default language option will help.
How you'll use it?

When Angular renders the default language, it uses the text messages that are embedded on the HTML and ignores the `messages.json` file, which I guess it's generated by the official extraction tool just to support the developer duplicating it to create the translations.

**Comment by gorenburg** [comment]
@marcioggs there are different approaches how you can handle translations. in our team we've used to the approach when you manually create files with translations and specify there key=value pairs. This means we manually create, for example, `learning.tutorial.messages.en.json` and specify all keys and value there, rather then using default angular translations extractor. this is rare usage case i would say

**Comment by marcioggs** [comment]
@gorenburg So you have the English text duplicated on the HTML files and on the key-value pair file?
Do you know that you can get rid of the key-value pair file for the language that's embedded in the source code and it will work the same way?

In my case, I also don't use the default extraction tool, and I create the `message.xx.json` files only for the translated languages to avoid extra work.

**Comment by marcioggs** [comment]
Regarding `--mergeFilename` argument:

We can add more flexibility by changing it to the following.
Are you available for implementing this? Otherwise, I can merge this PR as is and add these changes.

```
-ip, --id-prefix		Adds a prefix to the translation identifier based on the translation filename (see --id-prefix-strategy)
				[boolean] [default: false]

-ips, --id-prefix-strategy	Naming strategy applied to the translation filename to generate the identifier prefix (see --filename-delimiter)
				[string] [options: "camel-case", "as-is", "dot-case"] [default: "camel-case"]
```

We can use this library to help with changing the case:
https://github.com/blakeembrey/change-case

**Additional details:**
The `-ips` argument will consider both "-" and "." as word delimiters (e.g. both `learning.tutorial.messages.fr.json` and `learning-tutorial.messages.fr.json` will result in a prefix `learningTutorial` when `camel-case` strategy is used).
Initially, I thought of exposing the delimiter as an additional argument, but I think that this will just be added complexity for the reader of the docs without too much value.

I'm relying on the Angular docs to define some patterns and default values:

Options argument key separator: "-" e.g. `--browser-target` from https://angular.io/cli/extract-i18n
Options argument value separator: "-" e.g `--format legacy-migrate` from https://angular.io/cli/extract-i18n
Id prefix default naming strategy: camelCase e.g. `introductionHeader` from https://angular.io/guide/i18n-common-translation-files#translation-process-example-for-french
File name separator: "-" e.g. `product-list.component.ts` from https://angular.io/start

**Comment by marcioggs** [comment]
Great contribution @gorenburg 👍 
Once again, please let me know if you want me to continue and I'll happily do it by merging this PR as is (as I don't want this to be a burden to you).

**Comment by gorenburg** [comment]
@marcioggs yes, please. feel free to merge

**Comment by marcioggs** [comment]
@gorenburg 
Will work on this on the next days and will publish the new version after that.
Please just give me more info about the array bug when you have some time.

Feel free to submit other great ideas when you have them :)

**Comment by gorenburg** [comment]
@marcioggs sometimes with many options when running the command included it returns array for path splitting absolute path into [absolute_path, relative_path]

**Pull request merged**
